Apply React-router
balbalbaldevs/d.log pull request #33
Opened 2020-05-03 14:41 UTC by recordar

- Add Router.jsx into pages folder.
- Move App.jsx into pages folder.
- Add Home.jsx file. (+css, test file)

2020-05-04 04:05 UTC, r0o0 requested changes

2020-05-04 04:05 UTC, r0o0 commented on client/src/pages/Router.jsx
> +);
페이지가 여러개인데 `PAGE_URL`을 array로 관리하면 어떨까요? 
반복적으로 route 쓰는게 편리해질것 같고 또 redirect 하는 경우도 관리하기 좋을것 같아요. :)

```
const PAGE_URL = [
  { path: '/', key: 'ROOT', exact: true, component: Home },
  { 
     path: '/login', 
     key: 'LOGIN', 
     exact: false, 
     component: (props) => {
        if (user) { return <Redirect to="/" />; }
        if (error) { return <Redirect to="/404" />}
        return Login;
     }} 
  ...
]
```

저희 constant는 다 대문자로 쓸건가요? 아직 정해져있는건 없는데 이번에 정하고 가는게 좋을것 같아요.

2020-05-04 04:05 UTC, r0o0 commented on client/src/pages/Router.jsx
> +      <Redirect exact path={'/'} to={PAGE_URL.HOME} />
jsx에서 attribute에 `string` 값이 들어갈땐 `path="/"` 이렇게 쓰는걸 권장하고 있어요. 에디터 lint 세팅 고쳐서 이제 잡아줄거에요! :)

2020-05-04 04:05 UTC, r0o0 commented on client/src/pages/Home.jsx
> +  <div className="Home">
클래스명은 전부 소문자로 쓰는게 안햇갈리고 좋을것 같아요. :) 
convention은 bem을 썼으면 좋을것 같은데 의견 부탁드려요~

2020-05-04 04:05 UTC, r0o0 commented on client/src/pages/Home.jsx
> +    <header className="Home-header">
모든 페이지에 공통으로 들어갈 `nav`랑 `footer`는 어디에 넣을 예정인가요? 라우터 넣을때 정하고 가면 좋을것 같아요.
그거에 따라 Home 컴포넌트의 마크업 구조 수정이 필요할 수 있을것 같아요. :)

2020-05-04 04:07 UTC, r0o0 commented
pages안에 폴더로 한번 묶는게 관리하기 좋을것 같은데 어떡해 생각하세요?

/pages
  /Home
     Home.jsx
     Home.scss
     Home.test.js

2020-05-04 09:55 UTC, recordar commented on client/src/pages/Router.jsx
> +);
* 넵! constant 는 대문자가 좋을 것 같아요
* 제 생각엔 PAGE_URL 객체 따로, ROUTES array 따로 놓는게 어떨까 해염 :) 
PAGE_URL 은 export 해서 여기서 뿐만아니고 다른 페이지에서 페이지 이동 시 가져다 쓸 수 있을 것 같아서욤~
```
export const PAGE_URL = {
  ROOT: '/',
  LOGIN: '/login',
  ...
};

const ROUTES = [
  { path: PAGE_URL.ROOT, key: 'ROOT', exact: true, component: Home },
  { 
     path: PAGE_URL.LOGIN, 
     key: 'LOGIN',   // key 는 path 값으로 대체해도 되지 않을까요?ㅎㅎ
     exact: false, 
     component: (props) => {
        if (user) { return <Redirect to="/" />; }
        if (error) { return <Redirect to="/404" />}
        return Login;
     }} 
  ...
];

const Router = () => (
  <BrowserRouter>
    <Naviagtion/>
    <Switch>
      { ROUTES.map(({path, exact, component}) => <Route exact={exact} path={path} key={path} component={component}>) }
    </Switch>
    <Footer/>
  </BrowserRouter>
);

```

2020-05-04 09:56 UTC, recordar commented on client/src/pages/Router.jsx
> +      <Redirect exact path={'/'} to={PAGE_URL.HOME} />
아 ```{}``` 로 감싸가지구 린트에서 javascript string 으로 인식했나보네영ㅜㅜ
넵넵! 이부분은 PAGE_URL.ROOT 이걸로 대체하도록 할게욤 ㅎㅎ

2020-05-04 09:56 UTC, recordar commented on client/src/pages/Home.jsx
> +  <div className="Home">
좋아염! ㅎㅎ 👍

2020-05-04 09:59 UTC, recordar commented on client/src/pages/Home.jsx
> +    <header className="Home-header">
라우터 ```<Switch/>``` 바깥쪽에 위아래 넣는건 어떨까욤?
어차피 공통이면 페이지마다 그려주지 않아도 될것같공 ㅎㅎ
제가 네비, 푸터 없는 모바일 웹앱만 해봤었어가지공 고려를 못했었네요 ㅜㅜㅋㅋ
감사합니다!

2020-05-04 10:06 UTC, recordar commented
> pages안에 폴더로 한번 묶는게 관리하기 좋을것 같은데 어떡해 생각하세요?
> 
> /pages
> /Home
> Home.jsx
> Home.scss
> Home.test.js

넵넵 저도 폴더 구조로 가져가는게 좋을것 같아요~
다만,
```
pages/Home/index.jsx
pages/Home/Home.scss
pages/Home/Home.test.js
```

이렇게 가야 다른 라우터에서 페이지 임포트 시
```
import Home from './Home/Home'; // (x)
import Home from './Home'; // (o)
```

이렇게 경로가 폴더명으로만 끝낼 수 있을것 같아요ㅎㅎ
아니면
pages/index.js 로 페이지들 모을까요?

---------------------------------------

컴포넌트의 scss, test 파일은 보통 대문자로 시작하나용?
제가 했던 프로젝트에서는 컴포넌트는 대문자, scss, test 파일은 소문자로 시작했었어가지공..ㅎㅎ
의견 부탁드려욤 :)

2020-05-04 10:20 UTC, awesomeey commented on client/src/pages/Home.jsx
> +  <div className="Home">
ㄷㅏ른분들 참고하시라고 BEM 관련 링크 달아놓아요
https://junwoo45.github.io/2019-08-29-BEM/
https://velog.io/@yesdoing/BEM-Block-Element-Modifier-Quick-start

저도 좋아용!

2020-05-04 10:46 UTC, r0o0 commented on client/src/pages/Router.jsx
> +);
- 공유하는 constant들만 대문자로 하는건 어떨까요?
- 오호 `PAGE_URL`은 말씀하신것처럼 따로 빼는게 좋을것 같아요! :)

2020-05-04 11:06 UTC, r0o0 commented on client/src/pages/Home.jsx
> +    <header className="Home-header">
Router 컴포넌트는 이름도 그렇고 router만 처리하는게 좋을것 같아요. layout 종류가 한가지 밖에 없으니 `<Router />` 를 쓴데에 쓰는게 관리하기 더 좋을것 같아요. ㅎㅎ

2020-05-04 11:10 UTC, r0o0 commented
> > pages안에 폴더로 한번 묶는게 관리하기 좋을것 같은데 어떡해 생각하세요?
> > /pages
> > /Home
> > Home.jsx
> > Home.scss
> > Home.test.js
> 
> 넵넵 저도 폴더 구조로 가져가는게 좋을것 같아요~
> 다만,
> 
> ```
> pages/Home/index.jsx
> pages/Home/Home.scss
> pages/Home/Home.test.js
> ```
> 
> 이렇게 가야 다른 라우터에서 페이지 임포트 시
> 
> ```
> import Home from './Home/Home'; // (x)
> import Home from './Home'; // (o)
> ```
> 
> 이렇게 경로가 폴더명으로만 끝낼 수 있을것 같아요ㅎㅎ
> 아니면
> pages/index.js 로 페이지들 모을까요?
> 
> 컴포넌트의 scss, test 파일은 보통 대문자로 시작하나용?
> 제가 했던 프로젝트에서는 컴포넌트는 대문자, scss, test 파일은 소문자로 시작했었어가지공..ㅎㅎ
> 의견 부탁드려욤 :)

네 폴더 구조로 가면 index 폴더 만들어서 모으는게 좋을것 같아요 컴포넌트 처럼요 ㅎㅎ
이런식으로 많이 쓰는것 같아요!  :)
Home.jsx
Home.scss
Home.test.js

2020-05-05 04:00 UTC, recordar commented on client/src/pages/Home.jsx
> +    <header className="Home-header">
넵 그럼 이부분은 차후 컴포넌트 개발되면 App.jsx 에 넣는걸로 해욤 :))) 👍

2020-05-06 03:29 UTC, r0o0 approved these changes

2020-05-06 03:29 UTC, r0o0 approved these changes

2020-05-06 03:36 UTC, merged