Add Loading component (DL-10)
balbalbaldevs/d.log pull request #62
Opened 2020-07-05 09:33 UTC by r0o0

2020-07-19 03:02 UTC, codemacaron requested changes

2020-07-19 03:02 UTC, codemacaron commented on client/src/components/Loading/components/Spinner/Spinner.scss
> +  height: 20px;
spinner size를 대 중 소로 가능 하도록 작업 해주세요.

2020-07-19 03:02 UTC, codemacaron commented on client/src/components/Loading/Loading.tsx
> +      {type === LOADING_TYPE.TEXT && <Dots />}
text와 함께 사이즈를 대 중 소로 만들어 주세요.

2020-08-02 09:31 UTC, r0o0 commented on client/src/components/Loading/components/Spinner/Spinner.scss
> +  height: 20px;
좋은 아이디어 입니당! ㅎㅎ
'small' | 'medium' | 'large' 사이즈로  enum 등록하고 (47f860e) 수정했어요~ 6c75ff0

2020-08-02 09:33 UTC, r0o0 commented on client/src/components/Loading/Loading.tsx
> +      {type === LOADING_TYPE.TEXT && <Dots />}
text font-size에 맞게 dots 사이즈 알맞게 추가했어요. 6c75ff0

2020-08-02 10:24 UTC, r0o0 commented
StyleContainer의 direction 값이 default로 `horizontal`로 되어있더라구요;; 앞으로 이 컴포넌트 사용할대 햇갈릴것 같아서 `vertical`로 수정했어요. 이부분 수정하면서 Loading.md에 StyleContainter 쓸 수 있는 부분들도 수정했어요. 14ccd16

2020-08-06 13:47 UTC, codemacaron approved these changes

2020-08-07 15:04 UTC, merged