[DLB-18] 사용자 controller 구현
balbalbaldevs/d.log pull request #65
Opened 2020-07-15 23:27 UTC by EunbyulKo

2020-07-16 06:36 UTC, Electric-Fan submitted a review, later dismissed
확인 하였습니다.

2020-07-16 06:36 UTC, Electric-Fan commented on server/src/main/java/com/dlog/diary/common/domain/CommonDate.java
> +public class CommonDate {
저도 이렇게 구조 가져갈게요.

2020-07-16 06:36 UTC, Electric-Fan commented on server/src/main/resources/sql/goal.sql
> +CREATE TABLE `goal` (
저희 DDL을 프로젝트에 포함시키는것보다 다른 저장 장소를 찾아 보는게 어떨까요?

2020-07-16 12:22 UTC, r0o0 requested changes

2020-07-16 12:22 UTC, r0o0 commented on server/src/main/java/com/dlog/diary/user/dto/UserDto.java
> +	@ApiModelProperty(value="몸무게", example="50")
이 코드만 봤을 때 integer로만 값을 주는것 같은데 height와 weight의 단위는 따로 관리 하나요? 만약 없다면 저 값이 kg인지 lb인지 cm인지 inch 인지 관리하면 좋을것 같습니다. 추후에 사용자 설정 쪽에 단위 설정도 넣을 수 있으면 좋을것 같아요 ㅎㅎ

2020-07-18 11:06 UTC, EunbyulKo commented on server/src/main/resources/sql/goal.sql
> +CREATE TABLE `goal` (
다른 공간에 저장한다면 Notion에 추가해놓아도 좋을거 같아요. 
마이그레이션하는 SQL이나 DDL를 프로젝트에 포함해놓은걸 본적있음 + 관리편해보임
그래서 따라해보긴 했는데 다른 문제점이 있다면 얘기해주세요

packaging 시 제거하는건 생각하지도 못했는데 알려주셔서 감사합니다! >_<

2020-07-18 11:06 UTC, EunbyulKo commented on server/src/main/java/com/dlog/diary/user/dto/UserDto.java
> +	@ApiModelProperty(value="몸무게", example="50")
좋은 지적이십니다!
초반에 DB 설계할때 나온 얘기였어요. 운동 다이어리에서도 운동시간이 현재는 분 기준인데 나중에 시간이나 초도 필요할 수 있으니 단위도 DB에 넣을까하다가 구조 간단하게 가고 단위가 바뀔 확률도 적을거 같아서 나중에 추가하자로 결론이 났어요. 

DB 바꾸는건 조금 시간이 걸릴거 같음 -> 하지만 지라추가해서 나중에 DB에도 반영
UserDto에 hegihtUnit, weigthUnit을 추가하고 UnitType 타입도 추가할게요

추가한 다음 댓글 달아두겠습니당

2020-07-18 12:24 UTC, r0o0 submitted a review, later dismissed

2020-07-18 12:49 UTC, EunbyulKo commented on server/src/main/java/com/dlog/diary/user/dto/UserDto.java
> +	@ApiModelProperty(value="몸무게", example="50")
추가했습니다

2020-07-19 01:49 UTC, r0o0 commented on server/src/main/java/com/dlog/diary/user/dto/UserDto.java
> +	@ApiModelProperty(value="몸무게", example="50")
프론트는 서버에서 받은걸 쓰려고 생각하고 있어요 계획하고 계신 3번 혹은 2번이 좋을것 같습니다 :)

2020-07-23 05:39 UTC, tdman approved these changes

2020-07-23 05:40 UTC, tdman approved these changes

2020-07-23 05:43 UTC, bestFried approved these changes

2020-07-23 05:43 UTC, merged